version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    - image: circleci/mongo:latest
    - image: circleci/postgres:latest
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: circle_test

    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: cp .env.example .env
    - run: yarn install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Linter
        command: yarn lint

    - run:
        name: Test
        command: yarn junit

    - store_test_results:
        path: test-results
